import { Note } from '../types/note';

export const INITIAL_MOCK_NOTES: Note[] = [
  {
    id: 'note-welcome-1',
    noteType: 'text',
    title: '✨ StickyCraft Pro에 오신 것을 환영합니다!',
    content: `포스트잇의 친근한 아날로그 감성과 전문가용 기능이 결합된 프리미엄 스티커 메모 앱입니다.

💡 핵심 팁:
• [그리드 뷰]와 [캔버스 뷰]를 상단 우측 버튼으로 언제든 전환해 보세요.
• 캔버스 모드에서는 스티커를 손가락으로 자유롭게 드래그하여 원하는 위치에 배치할 수 있습니다!
• 메모를 탭하면 전체 내용을 1:1 전용 에디터로 크게 보고 편집할 수 있습니다.`,
    color: 'yellow',
    decoStyle: 'tape',
    images: [],
    checklist: [],
    tags: ['시작하기', '꿀팁'],
    isPinned: true,
    isLocked: false,
    boardId: 'ideas',
    canvasX: 20,
    canvasY: 30,
    zIndex: 1,
    rotation: -1.5,
    createdAt: Date.now() - 3600000 * 24,
    updatedAt: Date.now() - 3600000 * 24,
  },
  {
    id: 'note-checklist-demo',
    noteType: 'checklist',
    title: '✅ ColorNote 스타일 할 일 체크리스트',
    content: `[x] 상단 듀얼 뷰 스위치(그리드/캔버스) 눌러보기\n[ ] ColorNote 줄노트 에디터에서 음성 녹음해보기\n[ ] Notewise PDF 문서 뷰어에서 형광펜 칠하기\n[ ] DrawNote 무한 캔버스에서 마인드맵 연결선 그리기`,
    color: 'mint',
    decoStyle: 'minimal',
    images: [],
    checklist: [
      { id: 'c1', text: '상단 듀얼 뷰 스위치(그리드/캔버스) 눌러보기', completed: true },
      { id: 'c2', text: 'ColorNote 줄노트 에디터에서 음성 녹음해보기', completed: false },
      { id: 'c3', text: 'Notewise PDF 문서 뷰어에서 형광펜 칠하기', completed: false },
      { id: 'c4', text: 'DrawNote 무한 캔버스에서 마인드맵 연결선 그리기', completed: false },
    ],
    tags: ['체크리스트', 'ColorNote'],
    isPinned: true,
    isLocked: false,
    boardId: 'ideas',
    canvasX: 360,
    canvasY: 40,
    zIndex: 2,
    rotation: 1.2,
    createdAt: Date.now() - 3600000 * 18,
    updatedAt: Date.now() - 3600000 * 18,
  },
  {
    id: 'note-pdf-demo',
    noteType: 'pdf',
    title: '📄 2026 프로덕트 전략 로드맵.pdf',
    pdfName: '2026 프로덕트 전략 로드맵.pdf',
    content: `Goodnotes & Notewise 스타일 A4 멀티페이지 문서 뷰어입니다.
직접 페이지를 넘겨가며 고해상도 Bézier 형광펜 필기 및 주석을 남길 수 있습니다.`,
    color: 'paper',
    decoStyle: 'minimal',
    images: [],
    checklist: [],
    tags: ['PDF문서', 'Goodnotes', '학습'],
    isPinned: false,
    isLocked: false,
    boardId: 'study',
    canvasX: 40,
    canvasY: 420,
    zIndex: 3,
    rotation: -0.8,
    bookmarkedPages: [1],
    strokes: [
      {
        id: 'stk_pdf_1',
        tool: 'shape',
        shapeType: 'rect',
        color: '#2563EB',
        width: 2.5,
        pageIndex: 1,
        points: [],
        shapeStart: { x: 38, y: 340 },
        shapeEnd: { x: 680, y: 560 },
      },
      {
        id: 'stk_pdf_2',
        tool: 'highlighter',
        color: '#FACC15',
        width: 24,
        pageIndex: 1,
        points: [
          { x: 38, y: 155 },
          { x: 420, y: 155 },
        ],
      },
    ],
    textBoxes: [
      {
        id: 'tb_pdf_demo_1',
        x: 460,
        y: 185,
        text: '📌 벤치마크 핵심 기획 주석',
        fontSize: 14,
        color: '#1E293B',
        backgroundColor: '#FEF08A',
        pageIndex: 1,
      },
    ],
    audioNotes: [
      {
        id: 'audio-sample-roadmap-1',
        uri: 'https://actions.google.com/sounds/v1/ambiences/rain_heavy.ogg',
        duration: 48,
        createdAt: Date.now() - 3600000 * 2,
        pageIndex: 1,
        title: 'P.1 아키텍처 및 로드맵 핵심 기획',
        x: 52,
        y: 215,
      },
      {
        id: 'audio-sample-roadmap-2',
        uri: 'https://actions.google.com/sounds/v1/ambiences/coffee_shop.ogg',
        duration: 72,
        createdAt: Date.now() - 3600000 * 1,
        pageIndex: 3,
        title: 'P.3 v2.0 릴리즈 마일스톤 논의',
        x: 60,
        y: 350,
      },
    ],
    createdAt: Date.now() - 3600000 * 14,
    updatedAt: Date.now() - 3600000 * 14,
  },
  {
    id: 'note-canvas-demo',
    noteType: 'canvas',
    title: '🎨 DrawNote 스타일 자유 손글씨 & 스케치',
    content: `자유로운 만년필 벡터 드로잉과 형광펜, 모눈종이 속지가 적용된 드로잉 캔버스입니다.`,
    color: 'sky',
    decoStyle: 'tape',
    paperTemplate: 'grid',
    strokes: [
      {
        id: 'stk_1',
        tool: 'fountain',
        color: '#2563EB',
        width: 4,
        points: [
          { x: 40, y: 50 },
          { x: 80, y: 60 },
          { x: 130, y: 55 },
          { x: 180, y: 70 },
          { x: 220, y: 65 },
        ],
      },
      {
        id: 'stk_2',
        tool: 'highlighter',
        color: '#FACC15',
        width: 22,
        points: [
          { x: 35, y: 110 },
          { x: 250, y: 110 },
        ],
      },
    ],
    images: [],
    checklist: [],
    tags: ['손글씨', 'DrawNote', '스케치'],
    isPinned: false,
    isLocked: false,
    boardId: 'ideas',
    canvasX: 380,
    canvasY: 460,
    zIndex: 4,
    rotation: 1.5,
    createdAt: Date.now() - 3600000 * 10,
    updatedAt: Date.now() - 3600000 * 10,
  },
  {
    id: 'note-long-text-2',
    noteType: 'text',
    title: '📖 무제한 장문 텍스트 & 내부 스크롤',
    content: `이 스티커 메모는 글자 수 제한이 전혀 없으며, 메모 카드 내부에서 부드럽게 스크롤을 지원합니다!

스티커 메모 특유의 컴팩트한 비주얼을 유지하면서도, 논문 발췌, 소설 구상, 긴 회의록이나 칼럼을 마음껏 작성할 수 있습니다.

[장문 테스트 본문 1]
생각은 순간적으로 떠오르지만, 제대로 기록되지 않으면 쉽게 흩어집니다. 고도화된 스티커 메모 시스템은 아이디어의 시각적 형태를 유지하면서 필요한 모든 세부 내용을 담을 수 있는 최적의 그릇이 되어줍니다.`,
    color: 'lavender',
    decoStyle: 'pin',
    images: [],
    checklist: [],
    tags: ['장문기록', '스크롤'],
    isPinned: false,
    isLocked: false,
    boardId: 'work',
    canvasX: 200,
    canvasY: 820,
    zIndex: 5,
    rotation: -1.2,
    createdAt: Date.now() - 3600000 * 6,
    updatedAt: Date.now() - 3600000 * 6,
  },
];
